//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avion_Equipaje
    {
        public int Id { get; set; }
        public int Avion_Codigo { get; set; }
        public int Equipaje_Codigo_Equipaje { get; set; }
    
        public virtual Avion Avion { get; set; }
        public virtual Equipaje Equipaje { get; set; }
    }
}
