//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpleadoTalma
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmpleadoTalma()
        {
            this.Equipo_ServicioLimpieza = new HashSet<Equipo_ServicioLimpieza>();
            this.Equipo_ServicioRampa = new HashSet<Equipo_ServicioRampa>();
        }
    
        public int Codigo_Empleado { get; set; }
        public string Nombre { get; set; }
        public int DNI { get; set; }
        public string Usuario { get; set; }
        public string Contrasena { get; set; }
        public string Rango { get; set; }
        public string Rol { get; set; }
        public System.TimeSpan Hora_Inicio_Labores { get; set; }
        public System.TimeSpan Hora_Fin_Labores { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equipo_ServicioLimpieza> Equipo_ServicioLimpieza { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equipo_ServicioRampa> Equipo_ServicioRampa { get; set; }
    }
}
