//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipo_ServicioLimpieza
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipo_ServicioLimpieza()
        {
            this.ServiciosTalma_Vuelo = new HashSet<ServiciosTalma_Vuelo>();
        }
    
        public int Codigo_EpLimpienza { get; set; }
        public int EmpleadoTalma_Codigo { get; set; }
        public int Cantidad_Auxiliares { get; set; }
        public string Recursos_Empleados { get; set; }
        public string Tareas_Realizadas { get; set; }
        public string Comentarios { get; set; }
        public System.TimeSpan Hora_Inicio_Servicio_Limpieza { get; set; }
        public System.TimeSpan Hora_Fin_Servicio_Limpieza { get; set; }
    
        public virtual EmpleadoTalma EmpleadoTalma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiciosTalma_Vuelo> ServiciosTalma_Vuelo { get; set; }
    }
}
